### ISSUE TITLE
mutual dependency with Packer

### ISSUE THREAD

**Issue by danstender** [packer-community/winrmcp#12]
Hi Dylan,
we're packaging Packer for Debian and have a little problem with the mutual dependency between winrmcp and Packer. Packer imports the winrmcp sources to build and winrmcp needs the Packer sources (github.com/mitchellh/packer/common/uuid), so neither package could go into the archive first. When it's possible and you would have the time, could you change this upstream?
Best,
Daniel Stender

**Comment by dylanmei** [comment]
We can change the UUID dependency to something else. ID generation libraries in Go are a dime a dozen.

- https://github.com/rs/xid
- https://github.com/kjk/betterguid
- https://github.com/glycerine/ruid
- etc...

Would that suffice?

**Comment by danstender** [comment]
Hi Dylan, thx for the quick reply!

We've got hashicorp-go-uuid
          satori-go.uuid
          nu7hatch-gouuid
and       pborman-uuid in Debian now.

Bust just pick anything which fits best for you, I'll prepare another package no problem ...

Cheers,
Daniel

**Comment by dylanmei** [comment]
@danstender Commit 606243c91c0b1da7c23d1c054f13078217441a3b will clear up the dependency problem. :)

**Comment by danstender** [comment]
Yup, that's pretty slick! Thx much!

Dan
