### ISSUE TITLE
The first subdirectory of a folder upload is truncated when using relative paths

### ISSUE THREAD

**Issue by mefellows** [packer-community/winrmcp#2]
Given the current working dir 
```
~/go/src/github.com/packer-community/winrmcp
```

and a sub-directory 
```
DSC/Index_files/foo/bar
```

the command 
```
`bin/winrmcp -user=vagrant -pass=vagrant ./DSC c:/DSC`
```

will result in the following errant upload path:

```
c:/DSC/ex_files/foo/bar
```

I believe the root cause of this to be line 72 of [winrmcp.go](https://github.com/packer-community/winrmcp/blob/master/winrmcp/winrmcp.go#L72) which fails to take into consideration.

**Comment by mefellows** [comment]
Fixed, build passing (and also Tested in a Packer run).

**Comment by dylanmei** [comment]
Awesome thanks!
